# Generated by Django 4.1.3 on 2022-12-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snacks',
            name='image_url',
            field=models.TextField(default='no image'),
        ),
    ]
